config/routes.rb
Rails.application.routes.draw do
  #get 'sessions/new'
  root 'home#index'
  resources :users
  get 'login' => 'sessions#new'
  get 'logout' => 'sesions#destroy'
  post 'login' => 'sessions#create'

  #LOGIN: create a session (new_session_path)
  #LOGOUT: delete a session (destroy_session_path)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
require 'bcrypt'
class User < ApplicationRecord
  validates :email, presence:true, uniqueness: {case_sensitivity: false}
  #include BCrypt OR BCrypt::Password.create in password=value method
  #BCrypt::Password.create(value) doesn't create string even though its ""

  has_secure_password

  #has_secure_password is a rails helper which substitutes
  #all the method which are written down!

  # def password=(value)
  #   @password = value
  #   self.password_digest = BCrypt::Password.create(value)
  # end
  # 
  # def password
  #   @password
  # end
  # 
  # def valid_password?(current_password)
  #   #"asdfasfsd!4324f" == "asdf"
  #   # In other words, Hash digest == value
  #   #check the github page
  #   BCrypt::Password.new(password_digest) == current_password
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out(user)
    session[:user_id] = nil
  end

  def current_user
    #You do not want to hit the database(see below) everytime you call user
    #so check 1. return and if it is false assign @current_user = ........
    #User Load (2.0ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 5], ["LIMIT", 1]]
    #CACHE User Load (0.0ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 5], ["LIMIT", 1]]
    #CACHE User Load (0.0ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 5], ["LIMIT", 1]]

    return @current_user if @current_user

    if session[:user_id]
      @current_user = User.find(session[:user_id])
    else
      nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user
      if @user.authenticate(params[:password])
        log_in(@user)
        redirect_to root_path, flash: {notice: "Successfully logged in!"}
      else
        redirect_to login_path, flash: {notice: "Invalid password!"}
      end
    else
      redirect_to login_path, flash: {notice: "Invalid email"}
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #declaring helper method will make views use this method
  helper_method :current_user
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      log_in(@user)
      redirect_to root_path, flash: {success: "User created!"}
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<% if !current_user.nil? %>
  <br><h2>Welcome <%= current_user.name %></h2>
    <h3>PROFILE</h3><br>
    <h4>Email: <%= current_user.email %></h4>
<% else %>
    <h2>Welcome Guest!</h2>
  <%= link_to "Create an Account", new_user_path, class: "btn btn-primary" %>
  <%= link_to "Login", sessions_new_path, class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Authentication</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
  <div class="alert alert-warning"><%= flash[:notice]%></div>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
    <div class="form-group">
      <%= f.text_field :name, class: "form-control", placeholder: "Name" %><br>
    </div>

    <div class="form-group">
      <%= f.text_field :email, class: "form-control", placeholder: "Email"%><br>
    </div>

    <div class="form-group">
      <%= f.password_field :password, class:"form-control", placeholder: "Password" %><br>
    </div>

    <div class="form-group">
      <%= f.password_field :password_confirmation, class:"form-control", placeholder: "Password Confirmation" %><br>
    </div>

    <%= f.submit "Create Account", class: "btn btn-primary"%>
<% end %>

app/views/users/new.html.erb
<br><div class="card register-card">
  <div class="card-header">
    <h2 class="card-heading">Register</h2>
  </div>
  <div class="card-block">
    <% if @user.errors.any? %>
        <div class="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prevented this record from being saved:</h2>
          <ul class="user-errors"}>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <%end%>
    <%# pass user: @user, because if you use user: nil then the _form will crash %>
    <%= render 'form', user: @user %>
  </div>
</div>